language: c

matrix:
  include:
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
  - os: osx
  - os: linux
    dist: trusty
    env:
    - MAKEFILE_TARGET=distcheck
    - AUTOMAKE_VER=1.15
    - M4_VER=1.4.18
    - LIBTOOL_VER=2.4.6
  - os: linux
    env:
    - MAKEFILE_TARGET=dist
  - os: linux
    compiler: clang
    env:
    - CFLAGS_EXTRA="-O3 -march=native"
    - CONF_OPTIONS="--enable-assertions"
  - os: linux
    compiler: gcc
    env:
    - CFLAGS_EXTRA="-O3 -march=native"
    - CONF_OPTIONS="--enable-assertions"
  - os: osx
    env:
    - CFLAGS_EXTRA="-O3 -march=native"
    - CONF_OPTIONS="--enable-assertions"
  - os: linux
    compiler: clang
    dist: trusty
    env:
    - CFLAGS_EXTRA="-march=native -std=c11"
  - os: linux
    compiler: gcc
    env:
    - CFLAGS_EXTRA="-march=native -D _FORTIFY_SOURCE=2 -std=c89"
  - os: linux
    addons:
      apt:
        packages:
        - gcc-multilib
    compiler: clang
    env:
    - CFLAGS_EXTRA="-m32 -march=native"
    - CONF_OPTIONS="--enable-assertions"
  - os: linux
    addons:
      apt:
        packages:
        - gcc-multilib
    compiler: gcc
    env:
    - CFLAGS_EXTRA="-m32 -march=native"
    - CONF_OPTIONS="--enable-assertions"
  - os: osx
    env:
    - CFLAGS_EXTRA="-m32 -march=native -D _FORTIFY_SOURCE=2"
    - CONF_OPTIONS="--enable-assertions"
  - os: linux
    addons:
      apt:
        packages:
        - gcc-5
        - gcc-5-multilib
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc-5
    dist: trusty
    env:
    - CFLAGS_EXTRA="-mx32 -march=native -D _FORTIFY_SOURCE=2"
    - CONF_OPTIONS="--enable-assertions --enable-shared"
  - os: linux
    addons:
      apt:
        packages:
        - musl-tools
    compiler: musl-gcc
    dist: trusty
    env:
    - CFLAGS_EXTRA="-march=native"
    - CONF_OPTIONS="--enable-assertions"

before_install:
- if [[ "$AUTOMAKE_VER" != "" || "$LIBTOOL_VER" != "" || "$M4_VER" != "" ]]; then
    GNUTOOLS_ROOT=`pwd`/gnu-tools;
    export PATH=$GNUTOOLS_ROOT/bin:$PATH;
  fi
- if [[ "$M4_VER" != "" ]]; then
    M4_XZ_URL=https://ftp.gnu.org/gnu/m4/m4-$M4_VER.tar.xz;
    wget -O - $M4_XZ_URL | tar xf - --xz --directory ~;
    (cd ~/m4-$M4_VER && ./configure --prefix=$GNUTOOLS_ROOT && make -j check && make install);
  fi
- if [[ "$LIBTOOL_VER" != "" ]]; then
    LIBTOOL_XZ_URL=https://ftp.gnu.org/gnu/libtool/libtool-$LIBTOOL_VER.tar.xz;
    wget -O - $LIBTOOL_XZ_URL | tar xf - --xz --directory ~;
    (cd ~/libtool-$LIBTOOL_VER && ./configure --prefix=$GNUTOOLS_ROOT && make -j && make install);
  fi
- if [[ "$AUTOMAKE_VER" != "" ]]; then
    AUTOMAKE_XZ_URL=https://ftp.gnu.org/gnu/automake/automake-$AUTOMAKE_VER.tar.xz;
    wget -O - $AUTOMAKE_XZ_URL | tar xf - --xz --directory ~;
    (cd ~/automake-$AUTOMAKE_VER && ./configure --prefix=$GNUTOOLS_ROOT && make -j && make install);
  fi
- if [[ "$MAKEFILE_TARGET" == "dist"* ]]; then
    autoconf --version;
    automake --version;
    m4 --version;
    libtool --version || true;
  fi
- if [[ "$MAKEFILE_TARGET" == "" ]]; then MAKEFILE_TARGET=check; fi

install:
- "./autogen.sh"

script:
- ./configure $CONF_OPTIONS
- cat src/config.h
- make -j $MAKEFILE_TARGET CFLAGS_EXTRA="$CFLAGS_EXTRA"
- if [ -f tests/test_atomic.log ]; then cat tests/test_atomic*.log; fi
