language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CFLAGS_EXTRA_M=
  - CFLAGS_EXTRA="-O3 -march=native"
      CONF_ASSERTIONS=--enable-assertions
  - CFLAGS_EXTRA_M=-m32
      CFLAGS_EXTRA="-march=native"
      CONF_ASSERTIONS=--enable-assertions

matrix:
  exclude:
  - os: osx
    compiler: gcc

sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CFLAGS_EXTRA_M" == "-m32" ]]; then
      sudo apt-get install gcc-multilib;
    fi

install:
  - ./autogen.sh

script:
  - ./configure $CONF_ASSERTIONS
  - make -j check CFLAGS_EXTRA="$CFLAGS_EXTRA $CFLAGS_EXTRA_M"
  - if [ -f tests/test_atomic.log ]; then cat tests/test_atomic*.log; fi
