language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
  - os: osx
    compiler: gcc

sudo: false

install:
  - autoreconf -vif
  - ./configure

script:
  - make -j check
