language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CFLAGS_EXTRA_M=
  - CFLAGS_EXTRA="-O3 -march=native"
  - CFLAGS_EXTRA_M=-m32
    CFLAGS_EXTRA="-march=native"
  - CONF_GCOV=--enable-gcov

matrix:
  exclude:
  - os: osx
    compiler: gcc
  - compiler: clang
    env: CONF_GCOV=--enable-gcov

sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CFLAGS_EXTRA_M" == "-m32" ]]; then
      sudo apt-get install gcc-multilib;
    fi
  - if [[ "$CONF_GCOV" == --en* ]]; then
      sudo apt-get install lcov;
      gem install coveralls-lcov;
      CONF_SHARED=--disable-shared;
      CFLAGS_EXTRA="-march=native -DAO_TRACE_MALLOC -DVERBOSE";
    else
      CONF_ASSERTIONS=--enable-assertions;
    fi

install:
  - ./autogen.sh

script:
  - ./configure $CONF_ASSERTIONS $CONF_GCOV $CONF_SHARED --enable-werror
  - make -j check CFLAGS_EXTRA="$CFLAGS_EXTRA $CFLAGS_EXTRA_M"
  - if [ -f tests/test_atomic.log ]; then cat tests/test_atomic*.log; fi

after_success:
  - if [[ "$CONF_GCOV" == --en* ]]; then
      lcov --capture --directory src --directory tests --output-file coverage.info;
      lcov --remove coverage.info '/usr/*' 'tests/*' --output-file coverage.info;
      lcov --list coverage.info;
      coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info;
    fi
